# coding: utf-8
get_ipython().run_line_magic('load_ext', 'autoreload')
get_ipython().run_line_magic('autoreload', '2')
import load_dataset
import load_dataset
load_dataset.create_dataset(annotation_root_dir='/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/images', '/barn2/yuan/datasets/300W_LP_mini/json')
load_dataset.create_dataset('/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/images', '/barn2/yuan/datasets/300W_LP_mini/json')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
import numpy as np
img1  = np.load('/barn2/yuan/datasets/300W_LP_mini/heatmaps/samples/sample_hm11.png')
from scipy.ndimage import imread
img1  = imread('/barn2/yuan/datasets/300W_LP_mini/heatmaps/samples/sample_hm11.png')
img1
img1.max()
img1.min()
print(img1)
print(img1[20:40, 20:40])
print(img1[30:50, 35:55])
print(img1[25:45, 35:55])
imgs.dtype
img1.dtype
img1.shape
type(img1)
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
print(img1[30:50, 35:55])
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
img1  = imread('/barn2/yuan/datasets/300W_LP_mini/heatmaps/samples/sample_hm11.png')
print(img1[30:50, 35:55])
print(img1[20:50, 35:55])
print(img1[20:50, 20:55])
print(img1[39:50, 20:55])
print(img1[39:50, 10:55])
print(img1[39:50, 0:55])
print(img1[39:50, 0:60])
print(img1[39:50, 0:70])
print(img1[39:50, 0:80])
print(img1[39:50, 0:90])
img1.shape
print(img1[0:15, 0:90])
print(img1[15:30, 0:90])
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
img1  = imread('/barn2/yuan/datasets/300W_LP_mini/heatmaps/samples/sample_hm11.png')
img1  = imread('/barn2/yuan/datasets/300W_LP_mini/heatmaps/samples/sample_hm0.png')
print(img1[20:50, 35:55])
print(img1[20:50, 25:55])
print(img1[20:50, 25:35])
print(img1[20:50, 30:45])
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
h = 68
type(h)
type(h*3)
np.sqrt(h*h+h*h)
int(np.sqrt(h*h+h*h))
int(np.sqrt(h*h+h*h))
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP_mini/json', '/barn2/yuan/datasets/300W_LP_mini/annotations', '/barn2/yuan/datasets/300W_LP_mini/heatmaps')
img1  = imread('/barn2/yuan/datasets/300W_LP_mini/heatmaps/samples/sample_hm8.png')
img1[50:64, 20:40]
img1[50:64, 25:35]
img1[50:64, 30:40]
img1[50:65, 30:40]
img1[50:165, 30:40]
get_ipython().run_line_magic('ls', '')
load_dataset.create_heatmap_dataset('/barn2/yuan/datasets/300W_LP/json', '/barn2/yuan/datasets/300W_LP/annotations', '/barn2/yuan/datasets/300W_LP/heatmaps')
get_ipython().run_line_magic('save', '1-120')
