# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: training_hparam.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='training_hparam.proto',
  package='face_landmark.protos',
  serialized_pb=_b('\n\x15training_hparam.proto\x12\x14\x66\x61\x63\x65_landmark.protos\"{\n\x0bTrainConfig\x12\x1c\n\x10train_batch_size\x18\x01 \x01(\r:\x02\x32\x34\x12\x1d\n\rlearning_rate\x18\x02 \x01(\x02:\x06\x30.0001\x12\x13\n\x07\x65poches\x18\x03 \x01(\r:\x02\x31\x30\x12\x1a\n\reval_interval\x18\x04 \x01(\r:\x03\x31\x30\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRAINCONFIG = _descriptor.Descriptor(
  name='TrainConfig',
  full_name='face_landmark.protos.TrainConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_batch_size', full_name='face_landmark.protos.TrainConfig.train_batch_size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=24,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='face_landmark.protos.TrainConfig.learning_rate', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.0001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epoches', full_name='face_landmark.protos.TrainConfig.epoches', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_interval', full_name='face_landmark.protos.TrainConfig.eval_interval', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['TrainConfig'] = _TRAINCONFIG

TrainConfig = _reflection.GeneratedProtocolMessageType('TrainConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRAINCONFIG,
  __module__ = 'training_hparam_pb2'
  # @@protoc_insertion_point(class_scope:face_landmark.protos.TrainConfig)
  ))
_sym_db.RegisterMessage(TrainConfig)


# @@protoc_insertion_point(module_scope)
