# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63onfig.proto\"\xe4\x04\n\x1a\x46\x61\x63\x65LandmarkTrainingConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bnum_modules\x18\x02 \x01(\x05\x12\x11\n\tgpu_count\x18\x03 \x01(\x05\x12\x12\n\ninput_size\x18\x04 \x01(\x05\x12\x1a\n\x12use_image_gradient\x18\x05 \x01(\x08\x12\x16\n\x0e\x63onv1_channels\x18\x06 \x01(\x05\x12\x16\n\x0e\x63onv2_channels\x18\x07 \x01(\x05\x12\x16\n\x0e\x63onv3_channels\x18\x08 \x01(\x05\x12\x16\n\x0e\x63onv4_channels\x18\t \x01(\x05\x12\x18\n\x10num_landmark_pts\x18\n \x01(\x05\x12\x12\n\nstep_limit\x18\x0b \x01(\x05\x12\x16\n\x0elearning_rates\x18\x0c \x03(\x02\x12\x18\n\x10learning_epoches\x18\r \x03(\x05\x12\x1f\n\x17initial_checkpoint_path\x18\x0e \x01(\t\x12\x19\n\x11train_record_path\x18\x0f \x01(\t\x12\x18\n\x10\x65val_record_path\x18\x10 \x01(\t\x12\x18\n\x10train_batch_size\x18\x11 \x01(\x05\x12\x17\n\x0f\x65val_batch_size\x18\x12 \x01(\x05\x12\x13\n\x0btrain_sigma\x18\x13 \x01(\x02\x12\x12\n\neval_sigma\x18\x14 \x01(\x02\x12\x12\n\nexport_dir\x18\x15 \x01(\t\x12\x14\n\x0clog_filename\x18\x16 \x01(\t\x12\x1b\n\x13train_loss_interval\x18\x17 \x01(\x05\x12\x15\n\reval_interval\x18\x18 \x01(\x05\x12\x10\n\x08plot_dir\x18\x19 \x01(\tb\x06proto3')
)




_FACELANDMARKTRAININGCONFIG = _descriptor.Descriptor(
  name='FaceLandmarkTrainingConfig',
  full_name='FaceLandmarkTrainingConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='FaceLandmarkTrainingConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_modules', full_name='FaceLandmarkTrainingConfig.num_modules', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpu_count', full_name='FaceLandmarkTrainingConfig.gpu_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_size', full_name='FaceLandmarkTrainingConfig.input_size', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_image_gradient', full_name='FaceLandmarkTrainingConfig.use_image_gradient', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conv1_channels', full_name='FaceLandmarkTrainingConfig.conv1_channels', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conv2_channels', full_name='FaceLandmarkTrainingConfig.conv2_channels', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conv3_channels', full_name='FaceLandmarkTrainingConfig.conv3_channels', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conv4_channels', full_name='FaceLandmarkTrainingConfig.conv4_channels', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_landmark_pts', full_name='FaceLandmarkTrainingConfig.num_landmark_pts', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step_limit', full_name='FaceLandmarkTrainingConfig.step_limit', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='learning_rates', full_name='FaceLandmarkTrainingConfig.learning_rates', index=11,
      number=12, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='learning_epoches', full_name='FaceLandmarkTrainingConfig.learning_epoches', index=12,
      number=13, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initial_checkpoint_path', full_name='FaceLandmarkTrainingConfig.initial_checkpoint_path', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_record_path', full_name='FaceLandmarkTrainingConfig.train_record_path', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eval_record_path', full_name='FaceLandmarkTrainingConfig.eval_record_path', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_batch_size', full_name='FaceLandmarkTrainingConfig.train_batch_size', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eval_batch_size', full_name='FaceLandmarkTrainingConfig.eval_batch_size', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_sigma', full_name='FaceLandmarkTrainingConfig.train_sigma', index=18,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eval_sigma', full_name='FaceLandmarkTrainingConfig.eval_sigma', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='export_dir', full_name='FaceLandmarkTrainingConfig.export_dir', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_filename', full_name='FaceLandmarkTrainingConfig.log_filename', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_loss_interval', full_name='FaceLandmarkTrainingConfig.train_loss_interval', index=22,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eval_interval', full_name='FaceLandmarkTrainingConfig.eval_interval', index=23,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plot_dir', full_name='FaceLandmarkTrainingConfig.plot_dir', index=24,
      number=25, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=629,
)

DESCRIPTOR.message_types_by_name['FaceLandmarkTrainingConfig'] = _FACELANDMARKTRAININGCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FaceLandmarkTrainingConfig = _reflection.GeneratedProtocolMessageType('FaceLandmarkTrainingConfig', (_message.Message,), dict(
  DESCRIPTOR = _FACELANDMARKTRAININGCONFIG,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:FaceLandmarkTrainingConfig)
  ))
_sym_db.RegisterMessage(FaceLandmarkTrainingConfig)


# @@protoc_insertion_point(module_scope)
